<a href="https://colab.research.google.com/github/hshastri/PyTorchBasics/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np1

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.54980686, 0.62587281, 0.88152973, 0.88979388],
       [0.88194417, 0.85744961, 0.25832405, 0.63016898],
       [0.13048406, 0.94186318, 0.13496582, 0.83990462]])

In [ ]:
np1.dtype

dtype('float64')

In [ ]:
np1 = np.random.rand(3)
np1

array([0.53509391, 0.79678919, 0.91534773])

In [ ]:
tensor_2d = torch.randn(3,4)

In [ ]:
tensor_2d

tensor([[ 1.6107, -1.2449, -1.1750,  1.1519],
        [ 0.6993,  1.6288,  0.4082, -0.4779],
        [ 0.7032, -0.3315,  1.2233, -0.6890]])

In [ ]:
tensor_34 = torch.zeros(2,3,4)

In [ ]:
tensor_3d = tensor_34

In [ ]:
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
tensor_new = torch.tensor(np1)

In [ ]:
tensor_new

tensor([0.5351, 0.7968, 0.9153], dtype=torch.float64)

In [ ]:
tensor_new.dtype

torch.float64

In [ ]:
tensor_3d.dtype

torch.float32

In [ ]:
my_torcg = torch.arange(10)

In [ ]:
my_torcg

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# reshape and view
my_torch = my_torcg.reshape(2,5)

In [ ]:
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2 = torch.arange(10)

In [ ]:
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch3 = torch.arange(10)

In [ ]:
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch3.view(2,-5)

RuntimeError: invalid shape dimension -5

In [ ]:
my_torch3.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
a = torch.arange(10)

In [ ]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1] = 444

In [ ]:
a

tensor([  0, 444,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
a = torch.arange(10)

In [ ]:
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a.reshape(2,-1)

In [ ]:
b

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
a[1] = 404

In [ ]:
a

tensor([  0, 404,   2,   3,   4,   5,   6,   7,   8,   9])

In [ ]:
b

tensor([[  0, 404,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [ ]:
a[1]

tensor(404)

In [ ]:
a.slice(0,3)

AttributeError: 'Tensor' object has no attribute 'slice'

In [ ]:
a.reshape(5,2)

tensor([[  0, 404],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [ ]:
b = a.reshape(5,2)

In [ ]:
b[:,1]

tensor([404,   3,   5,   7,   9])

In [ ]:
b[:1]

tensor([[  0, 404]])

In [ ]:
b[:,1:]

tensor([[404],
        [  3],
        [  5],
        [  7],
        [  9]])

In [ ]:
a = torch.tensor([1,2,3,4])

In [ ]:
b = torch.tensor([5,6,7,8])

In [ ]:
a

tensor([1, 2, 3, 4])

In [ ]:
b

tensor([5, 6, 7, 8])

In [ ]:
a + b

tensor([ 6,  8, 10, 12])

In [ ]:
 torch.add(a, b)

tensor([ 6,  8, 10, 12])

In [ ]:
a - b

tensor([-4, -4, -4, -4])

In [ ]:
b - a

tensor([4, 4, 4, 4])

In [ ]:
torch.sub(b, a)

tensor([4, 4, 4, 4])

In [ ]:
a * b

tensor([ 5, 12, 21, 32])

In [ ]:
torch.mul(a, b)

tensor([ 5, 12, 21, 32])

In [ ]:
b / a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
b // a

tensor([5, 3, 2, 2])

In [ ]:
torch.div(a, b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [ ]:
b % a

tensor([0, 0, 1, 0])

In [ ]:
torch.remainder(b, a)

tensor([0, 0, 1, 0])

In [ ]:
a ^ b

tensor([ 4,  4,  4, 12])

In [ ]:
torch.pow(a, b)

tensor([    1,    64,  2187, 65536])

In [ ]:
a

tensor([1, 2, 3, 4])

In [ ]:
b

tensor([5, 6, 7, 8])

In [ ]:
a ^ b

tensor([ 4,  4,  4, 12])

In [ ]:
b ^ a

tensor([ 4,  4,  4, 12])

In [ ]:
# ^ is XOR operation not power

In [ ]:
a.add(b)

tensor([ 6,  8, 10, 12])

In [ ]:
a.add_(b)

tensor([ 6,  8, 10, 12])

In [ ]:
a

tensor([ 6,  8, 10, 12])